# .cnb.yml
build:
  builder: cnb/python-3.11
  buildpacks:
    - name: python-buildpack
      version: latest
  env:
    PYTHONUNBUFFERED: "1"
    FLASK_APP: app.py

run:
  command: gunicorn --bind 0.0.0.0:$PORT app:app
  ports:
    - 8080
  env:
    PORT: 8080
    FLASK_ENV: production